
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: chuyenBayService
        uri: http://localhost:8081/
        predicates:
        - Path=/chuyenbay/**
      - id: mayBayService
        uri: http://localhost:8082/
        predicates:
        - Path=/maybay/**